"""Generate the release STEP packet for custom-machined/RFQ parts.

These are manufacturing sources, not collision-only placeholders.  Every
export is a single solid and is paired with a dimensioned PDF generated by
``custom_drawings.py``.  Threads remain cosmetic envelopes, but every bearing,
shaft, wire-contact, flat, and face datum is dimensioned in the drawing.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

from build123d import (
    Align,
    Cylinder,
    export_step,
)

from params import DEFAULT_STATOR
import cots
import assembly
import flyer_shaft_d10


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "out" / "custom" / "step"
CTR = (Align.CENTER, Align.CENTER, Align.CENTER)

PART_METADATA = {
    "fixed_eyelet_id4_od9_t3": {
        "artifact_id": "fixed-ceramic-eyelet-id4-od9",
        "drawing": "output/pdf/fixed_eyelet_id4_od9_t3.pdf",
        "scope": "one fixed entry wire guide plus one fragile-part spare",
        "supplier_sku": None,
    },
    "shaft8_socket_holder": {
        "artifact_id": "m1-spindle-custom-d8-c8-100l",
        "drawing": "output/pdf/shaft8_socket_holder.pdf",
        "scope": "exact 8.00 mm stator-shaft endpoint only",
        "supplier_sku": None,
    },
    "flyer_shaft_d10_id6_to_id9_l79": {
        "artifact_id": "m2-flyer-shaft-stock-d10-rev-d",
        "drawing": "output/pdf/flyer_shaft_d10_id6_to_id9_l79.pdf",
        "scope": (
            "normal-GOAL stock-D10 flyer: full 18.5 mm round clamp seat, "
            "ID6-to-ID9 wire transition, and two printed-arm flats"
        ),
        "supplier_sku": None,
    },
}


def _tube(outer_d: float, inner_d: float, length: float):
    return (Cylinder(outer_d / 2.0, length, align=CTR)
            - Cylinder(inner_d / 2.0, length + 2.0, align=CTR))


def custom_t8_lead_screw():
    """Tr8x8(P2) four-start screw envelope with native Ø8x30 journal."""
    # Both zones originate from the same Ø8 blank.  The manufacturing PDF
    # distinguishes the lower 158 mm threaded region from the untouched 30 mm
    # journal; a fake helical thread would not improve interface validation.
    part = Cylinder(4.0, 188.0, align=(Align.CENTER, Align.CENTER, Align.MIN))
    part.label = "t8x8_leadscrew_188_journal30"
    return part


def flyer_tube_with_flats():
    """Compatibility seam returning the selected Rev-D stock-D10 shaft."""

    return flyer_shaft_d10.flyer_shaft()


def _spacer(od: float, inner: float, length: float, label: str):
    part = _tube(od, inner, length)
    part.label = label
    return part


def release_parts():
    parts = {
        "fixed_eyelet_id4_od9_t3": cots.ceramic_eyelet(
            label="fixed_eyelet_id4_od9_t3"
        ),
        "shaft_wrap_sleeve_d4": cots.ceramic_shaft_wrap_sleeve(
            DEFAULT_STATOR
        ),
        "t8x8_leadscrew_188_journal30": custom_t8_lead_screw(),
        "flyer_shaft_d10_id6_to_id9_l79": flyer_shaft_d10.flyer_shaft(),
        "shaft8_socket_holder": assembly.shaft8_socket_holder(),
        "m0_fixed_collar": cots.m0_fixed_clamp_collar(),
        "m0_inner_shim": _spacer(12.0, 8.10, 1.0, "m0_inner_shim"),
        "m1_outer_race_spacer": _spacer(
            21.8, 18.2, 16.0, "m1_outer_race_spacer"
        ),
        "m1_inner_race_spacer": _spacer(
            17.8, 8.05, 16.0, "m1_inner_race_spacer"
        ),
        "m1_lower_inner_spacer": _spacer(
            17.8, 8.05, 12.0, "m1_lower_inner_spacer"
        ),
        "m1_upper_collar": cots.shaft_clamp_collar(
            16.0, 8.05, 9.0, label="m1_upper_collar"
        ),
        "m2_outer_race_spacer": _spacer(
            27.8, 22.0, 11.0, "m2_outer_race_spacer"
        ),
        "m2_rear_shim": _spacer(18.0, 12.05, 0.5, "m2_rear_shim"),
        "m2_center_inner_spacer": _spacer(
            17.8, 12.05, 11.0, "m2_center_inner_spacer"
        ),
        "m2_front_inner_spacer": _spacer(
            18.0, 12.05, 4.0, "m2_front_inner_spacer"
        ),
    }
    for name, part in parts.items():
        part.label = name
    return parts


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    if OUT.resolve().parents[1] != (ROOT / "out").resolve():
        raise RuntimeError(f"refusing unexpected custom output path {OUT}")
    for old in OUT.glob("*.step"):
        old.unlink()
    records = []
    for name, part in release_parts().items():
        solids = len(part.solids())
        if solids != 1:
            raise RuntimeError(f"{name} has {solids} solids; expected one")
        path = OUT / f"{name}.step"
        export_step(part, str(path))
        bb = part.bounding_box()
        record = {
            "id": name,
            "file": path.relative_to(ROOT).as_posix(),
            "sha256": _sha256(path),
            "bytes": path.stat().st_size,
            "single_solid": True,
            "bbox_mm": [
                round(bb.max.X - bb.min.X, 4),
                round(bb.max.Y - bb.min.Y, 4),
                round(bb.max.Z - bb.min.Z, 4),
            ],
        }
        record.update(PART_METADATA.get(name, {}))
        records.append(record)
        print(f"{name}: {record['bbox_mm']} mm -> {path.name}")
    manifest = OUT.parent / "manifest.json"
    manifest.write_text(json.dumps({"schema": 1, "parts": records}, indent=2)
                        + "\n", encoding="utf-8")
    print(manifest)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
